package org.example.project.user

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The id column is automatically generated by IntIdTable (see UserDAO.kt)
 */

@Serializable
data class User (
    @SerialName("user_name")
    val userName: String?,
    @SerialName("user_email")
    val userEmail: String?,
    @SerialName("user_password")
    val userPassword: String?) {
}